micronaut:
  application:
    name: lojaService
  server:
    port: ${SERVER_PORT:8081}

netty:
  default:
    allocator:
      max-order: 3

redis:
  uri: ${REDIS_URI:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:lojaService}

kafka:
  bootstrap:
    servers: ${KAFKA_SERVER:localhost}:${KAFKA_PORT:9092}

consul:
  client:
    registration:
      enabled: ${CONSUL_ENABLED:true}
    default-zone:
      - ${CONSUL_DEFAULT_ZONE:localhost}:${CONSUL_PORT:8500}