micronaut:
  application:
    name: lojaService
  server:
    port: 8081

netty:
  default:
    allocator:
      max-order: 3

redis:
  uri: redis://localhost
  port: 6379
  password: lojaService

kafka:
  bootstrap:
    servers: localhost:9092

consul:
  client:
    registration:
      enabled: true
    default-zone:
      - localhost:8500